sudo: required

language: generic

git:
  depth: false

dist:
  xenial

cache:
  directories:
    - $HOME/.m2

services:
  - docker

before_install:
  - docker pull moussavdb/build-java-native
  - chmod +x $PWD/src/main/scripts/linux64/build.sh

script:
  - $PWD/src/main/scripts/linux64/build.sh
  - docker run -v $PWD:/src -v $HOME/.m2:/root/.m2 -e BRANCH=$TRAVIS_BRANCH  -e VAULT_TOKEN=$VAULT_TOKEN moussavdb/build-java ./deploy-maven-central.sh
